isPublic: true
name: 'Public Schema'
scope:
  - 'sites.a4a834fb-b21b-4bd4-a9fe-6c7a696309ca:read' # Castor Groomer
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.24c06c0e-6a0f-4b7d-8a22-5824165c1a50:read' # Pagina's
  - 'nestedentryfields.10239a61-a58c-48f2-aa32-6881afa33bdb:read' # Pagina inhoud
  - 'volumes.23e3516b-6472-4242-bbc1-e13872d98943:read' # Algemeen
