import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const navitems = [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "Het salon",
      href: "/het-salon",
    },
    {
      label: "Behandelingen",
      href: "/behandelingen",
    },
    {
      label: "Katten trimmen",
      href: "/katten-trimmen",
    },
    {
      label: "Puppie gewenning",
      href: "/puppie-gewenning",
    },
    {
      label: "Huisregels",
      href: "/huisregels",
    },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='p-4'>
          <nav className="flex gap-4">
            {navitems.map((item) => (
              <Link className="text-periwinkle-900 text-semibold px-4 py-2 rounded-md" key={item.href} href={item.href}>{item.label}</Link>
            ))}
          </nav>
        </header>
        <div className="p-2 w-48 bg-periwinkle-100 text-center mb-1">
          <p>periwinkle 100</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-200 text-center mb-1">
          <p>periwinkle 200</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-300 text-center mb-1">
          <p>periwinkle 300</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-400 text-center mb-1">
          <p>periwinkle 400</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-500 text-center mb-1">
          <p>periwinkle 500</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-600 text-center mb-1">
          <p>periwinkle 600</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-700 text-center mb-1">
          <p>periwinkle 700</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-800 text-center mb-1">
          <p>periwinkle 800</p>
        </div>
        <div className="p-2 w-48 bg-periwinkle-900 text-center mb-4">
          <p>periwinkle 900</p>
        </div>

        <div className="p-2 w-48 bg-bittersweet-shimmer-100 text-white text-center mb-1">
          <p>bittersweet 100</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-200 text-white text-center mb-1">
          <p>bittersweet 200</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-300 text-white text-center mb-1">
          <p>bittersweet 300</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-400 text-white text-center mb-1">
          <p>bittersweet 400</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-500 text-white text-center mb-1">
          <p>bittersweet 500</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-600 text-center mb-1">
          <p>bittersweet 600</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-700 text-center mb-1">
          <p>bittersweet 700</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-800 text-center mb-1">
          <p>bittersweet 800</p>
        </div>
        <div className="p-2 w-48 bg-bittersweet-shimmer-900 text-center mb-4">
          <p>bittersweet 900</p>
        </div>

        <div className="p-2 w-48 bg-coyote-100 text-white text-center mb-1">
          <p>coyote 100</p>
        </div>
        <div className="p-2 w-48 bg-coyote-200 text-white text-center mb-1">
          <p>coyote 200</p>
        </div>
        <div className="p-2 w-48 bg-coyote-300 text-white text-center mb-1">
          <p>coyote 300</p>
        </div>
        <div className="p-2 w-48 bg-coyote-400 text-white text-center mb-1">
          <p>coyote 400</p>
        </div>
        <div className="p-2 w-48 bg-coyote-500 text-white text-center mb-1">
          <p>coyote 500</p>
        </div>
        <div className="p-2 w-48 bg-coyote-600 text-center mb-1">
          <p>coyote 600</p>
        </div>
        <div className="p-2 w-48 bg-coyote-700 text-center mb-1">
          <p>coyote 700</p>
        </div>
        <div className="p-2 w-48 bg-coyote-800 text-center mb-1">
          <p>coyote 800</p>
        </div>
        <div className="p-2 w-48 bg-coyote-900 text-center mb-4">
          <p>coyote 900</p>
        </div>

        <div className="p-2 w-48 bg-misty-rose-100 text-white text-center mb-1">
          <p>misty-rose 100</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-200 text-white text-center mb-1">
          <p>misty-rose 200</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-300 text-white text-center mb-1">
          <p>misty-rose 300</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-400 text-center mb-1">
          <p>misty-rose 400</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-500 text-center mb-1">
          <p>misty-rose 500</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-600 text-center mb-1">
          <p>misty-rose 600</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-700 text-center mb-1">
          <p>misty-rose 700</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-800 text-center mb-1">
          <p>misty-rose 800</p>
        </div>
        <div className="p-2 w-48 bg-misty-rose-900 text-center mb-4">
          <p>misty-rose 900</p>
        </div>
        {children}
      </body>
    </html>
  );
}
