columnSuffix: null
handle: pageContentGrid
instructions: null
name: 'Pagina inhoud'
searchable: false
settings:
  createButtonLabel: 'Nieuw blok toevoegen'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 13c3e668-ea49-4271-9ce3-ae47d32275c3 # Pagina hoofding
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
