altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  22c20340-0cb2-449c-8736-b2bc6399e58b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-01T18:26:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8995d381-3357-4057-b586-c4bfc47c7dde
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42dc5452-3b36-4693-a043-fc50515951c8
        userCondition: null
fs: site
handle: site
name: Algemeen
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
